// ─────────────────────────────────────────────────────────────────────────────
// Job Board Service — Ashby + Greenhouse
// Server proxy at /api/jobs handles all fetching (bypasses browser CORS).
// ─────────────────────────────────────────────────────────────────────────────

export interface AshbyJob {
  id: string;
  title: string;
  company: string;
  companyHandle: string;
  department: string;
  location: string;
  isRemote: boolean;
  employmentType: string;
  publishedDate: string; // YYYY-MM-DD or ISO timestamp
  source: 'ashby' | 'greenhouse' | 'lever';
  salary?: string;
  logoUrl?: string;
  applyUrl: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Company handles — edit this list to add or remove companies.
// Each string must match the Ashby job board subdomain handle.
// ─────────────────────────────────────────────────────────────────────────────
export const ASHBY_COMPANIES: string[] = [
  '1password',
  '9fin',
  'A1%20Garage%20Door%20Service',
  'Acorns',
  'Adtucon',
  'AlephAlpha',
  'Anon',
  'basis-ai',
  'BranchInsurance',
  'Cambly',
  'Clicklease',
  'Commure-Athelas',
  'credal',
  'Crusoe',
  'CylinderHealth',
  'Dashworks',
  'DatologyAI',
  'DeepL',
  'Deepgram',
  'Distyl',
  'Doowii',
  'DoseSpot',
  'FURTHER',
  'FlutterFlow',
  'Fourier',
  'GPTZero',
  'GoHenry',
  'GradientNetwork',
  'InscribeAI',
  'Jerry',
  'Juicebox',
  'LeanTech',
  'OpenSea',
  'Parkade',
  'Roam',
  'Secoda',
  'Siro',
  'Sonio',
  'Speakeasy',
  'StandardBots',
  'Stepful',
  'Tabs',
  'The-Flex',
  'Vultron',
  'aescape',
  'airapps',
  'airwallex',
  'alan',
  'almedia',
  'altimate',
  'altura',
  'amper',
  'anglehealth',
  'anima',
  'ankorstore',
  'anrok',
  'apify',
  'aptosfoundation',
  'arcade',
  'articul8',
  'artsy',
  'ashby',
  'assembledhq',
  'astera',
  'atob',
  'atroposhealth',
  'auger',
  'august-health',
  'axiom',
  'bankjoy',
  'beam',
  'bedrockocean',
  'benepass',
  'bestow',
  'bettermile',
  'bifrost',
  'blockhouse',
  'blockworks',
  'blueberrypediatrics',
  'boon',
  'botanictonics',
  'brainco',
  'brainly',
  'bratte',
  'bridge',
  'brigit',
  'bunch',
  'cantina',
  'capimoney',
  'captions',
  'carry',
  'casca',
  'centari',
  'character',
  'chronospherejobs',
  'cinder',
  'claylabs',
  'cluely',
  'cohere',
  'cointracker',
  'column',
  'comind',
  'compa',
  'comulate',
  'comun',
  'corti',
  'counsel',
  'count',
  'dakota',
  'dandy',
  'dave',
  'davidenergy',
  'decagon',
  'dedale',
  'deductive',
  'deel',
  'deepwalk',
  'delian',
  'devsavant',
  'dolarapp',
  'doppel',
  'dust',
  'earnedwealth',
  'ekumenlabs',
  'elevenlabs',
  'ema',
  'empora',
  'endex',
  'enode',
  'eotlabs',
  'equi',
  'equip',
  'everai',
  'evertune',
  'fable',
  'farmraise',
  'feathr',
  'fermat',
  'finalis',
  'finary',
  'finch',
  'finvest',
  'fleetpulse',
  'franki',
  'freshpaint',
  'fullstory',
  'g2i',
  'growthtroops',
  'guaranteed',
  'handshake',
  'handspring',
  'harvey',
  'hawk',
  'hcompany',
  'heyjobs',
  'hiive',
  'hims-and-hers',
  'horizon3ai',
  'hotplate',
  'humaans',
  'ideogram',
  'immersivelabs',
  'improbable',
  'integrationapp',
  'invert',
  'january',
  'jigsaw',
  'join9am',
  'joko',
  'julius',
  'junipersquare',
  'keeper',
  'keyrock',
  'kindred',
  'kovo',
  'kraken.com',
  'krea',
  'kustomer',
  'landbase',
  'latitude',
  'leland',
  'letta',
  'lightning',
  'lightspark',
  'lilt',
  'limble',
  'lindushealth',
  'listenlabs',
  'liveflow',
  'lmarena',
  'lucidlink',
  'luma-ai',
  'lunar',
  'mach',
  'mach9',
  'magiceden',
  'magicschool',
  'mainshares',
  'mandolin',
  'mangomint',
  'masabi',
  'mazehq',
  'menlosecurity',
  'metalenz',
  'middesk',
  'mintlify',
  'modernfi',
  'moderntreasury',
  'moego',
  'monarchmoney',
  'mondoo',
  'montecarlodata',
  'mosey',
  'mystenlabs',
  'n8n',
  'netboxlabs',
  'netic',
  'neworbit',
  'niramedical',
  'nomic',
  'notable',
  'numeric',
  'olive',
  'omnea',
  'omniscient',
  'oneapp',
  'onebrief',
  'openai',
  'opengov',
  'oplabs',
  'optery',
  'opusclip',
  'orbitalmaterials',
  'oumi',
  'outliant',
  'pacificfusion',
  'parabola-io',
  'parallel',
  'partiful',
  'partisiablockchain',
  'passage',
  'patreon',
  'peek',
  'phylax',
  'plain',
  'plasmidsaurus',
  'playai',
  'polygon-labs',
  'posthog',
  'primer',
  'privy',
  'projectgrowth',
  'proofofplay',
  'propelus',
  'protege',
  'pylon-labs',
  'quicknode',
  'qventus',
  'raiku',
  'ramp',
  'ravio',
  'reddit',
  'reflectionai',
  'reka',
  'remberg',
  'replit',
  'replo',
  'rilla',
  'rockerbox',
  'rocketsciencegg',
  'rogo',
  'rooser',
  'rula',
  'sardine',
  'scaler',
  'scrollmark',
  'seconddinner',
  'sensmore',
  'sentilink',
  'sesame',
  'siena',
  'silver',
  'skydropx',
  'sleeper',
  'slingshotai',
  'slope',
  'smalls',
  'solace',
  'sona',
  'speak',
  'sprig',
  'stainlessapi',
  'statsig',
  'stealthventurecapitalfirm',
  'stedi',
  'stickermule',
  'stream',
  'suno',
  'supabase',
  'superdial',
  'superduper',
  'surreal',
  'suzy',
  'svix',
  'symbiotic',
  'syndr',
  'synthflow',
  'system2',
  'talentful',
  'tandem',
  'tapcart',
  'taptapsend',
  'tarro',
  'tenex',
  'thatgamecompany',
  'thirstysprout',
  'tonal',
  'traba',
  'tryvital',
  'turnstile',
  'twelve',
  'udisc',
  'uipath',
  'valeriehealth',
  'vanta',
  'vapi',
  'virtahealth',
  'virtuous',
  'vitalize',
  'voladynamics',
  'vooma',
  'wander',
  'warp',
  'waterplan',
  'wayflyer',
  'weave',
  'welltech',
  'winona',
  'withclutch',
  'withpulley',
  'worldlabs',
  'writer',
  'xbowcareers',
  'xoul',
  'yondr',
  'yutori',
  'zapier',
  'zefir',
  'zefr',
  'zencastr',
  'zyphra',
];

// ─────────────────────────────────────────────────────────────────────────────
// Greenhouse company handles (boards.greenhouse.io/v1/boards/{handle}/jobs)
// Confirmed to have PM roles as of May 2026.
// ─────────────────────────────────────────────────────────────────────────────
export const GREENHOUSE_COMPANIES: string[] = [
  // Confirmed PM roles
  'airbnb', 'benchling', 'brex', 'carta', 'chime', 'coinbase', 'databricks',
  'discord', 'doordash', 'dropbox', 'duolingo', 'faire', 'fastly', 'figma',
  'flexport', 'gofundme', 'gusto', 'headspace', 'hubspot', 'instacart',
  'klaviyo', 'lyft', 'masterclass', 'mercury', 'modernhealth', 'mongodb',
  'navan', 'okta', 'pagerduty', 'patreon', 'peloton', 'pinterest', 'podium',
  'postman', 'quora', 'reddit', 'retool', 'robinhood', 'rubrik', 'sentry',
  'servicetitan', 'snyk', 'squarespace', 'stripe', 'thoughtspot', 'tipalti',
  'toast', 'twilio', 'twitch', 'udemy', 'vimeo', 'webflow', 'whoop',
  'wiz', 'workato', 'wrike',
  // Additional
  'amplitude', 'canva', 'coda', 'confluent', 'coursera', 'descript', 'etsy',
  'gem', 'heap', 'hex', 'hopin', 'ironclad', 'lob', 'looker', 'mixpanel',
  'nerdwallet', 'notion', 'opendoor', 'outreach', 'pilot', 'plaid', 'ramp',
  'segment', 'shopify', 'sourcegraph', 'superhuman', 'talkdesk', 'teachable',
  'unqork', 'wealthsimple', 'zendesk',
  // Expanded
  'cloudflare', 'elastic', 'box', 'unity', 'roblox', 'snap', 'justworks',
  'checkr', 'gitlab', 'netlify', 'rippling', 'datadog', 'asana', 'miro',
  'airtable', 'loom', 'intercom', 'braze', 'drift', 'gong', 'highspot',
  'lattice', 'pendo', 'contentful', 'algolia', 'sprinklr', 'medallia',
  'zuora', 'seismic', 'fivetran', 'hashicorp', 'cockroachdb', 'airbyte',
  'temporal', 'vercel', 'linear', 'dbtlabs', 'grafana',
];

// ─────────────────────────────────────────────────────────────────────────────
// Lever company handles (api.lever.co/v0/postings/{handle}?mode=json)
// ─────────────────────────────────────────────────────────────────────────────
export const LEVER_COMPANIES: { handle: string; name: string; domain: string }[] = [
  { handle: 'anthropic',    name: 'Anthropic',    domain: 'anthropic.com' },
  { handle: 'attentive',    name: 'Attentive',    domain: 'attentivemobile.com' },
  { handle: 'highspot',     name: 'Highspot',     domain: 'highspot.com' },
  { handle: 'clari',        name: 'Clari',        domain: 'clari.com' },
  { handle: 'intercom',     name: 'Intercom',     domain: 'intercom.com' },
  { handle: 'miro',         name: 'Miro',         domain: 'miro.com' },
  { handle: 'airtable',     name: 'Airtable',     domain: 'airtable.com' },
  { handle: 'loom',         name: 'Loom',         domain: 'loom.com' },
  { handle: 'lattice',      name: 'Lattice',      domain: 'lattice.com' },
  { handle: 'pendo',        name: 'Pendo',        domain: 'pendo.io' },
  { handle: 'gong-io',      name: 'Gong',         domain: 'gong.io' },
  { handle: 'dbtlabs',      name: 'dbt Labs',     domain: 'getdbt.com' },
  { handle: 'cockroachdb',  name: 'CockroachDB',  domain: 'cockroachlabs.com' },
  { handle: 'fivetran',     name: 'Fivetran',     domain: 'fivetran.com' },
  { handle: 'rippling',     name: 'Rippling',     domain: 'rippling.com' },
  { handle: 'airbyte',      name: 'Airbyte',      domain: 'airbyte.com' },
  { handle: 'linear',       name: 'Linear',       domain: 'linear.app' },
  { handle: 'vercel',       name: 'Vercel',       domain: 'vercel.com' },
  { handle: 'temporal',     name: 'Temporal',     domain: 'temporal.io' },
  { handle: 'grafana',      name: 'Grafana Labs', domain: 'grafana.com' },
  { handle: 'hashicorp',    name: 'HashiCorp',    domain: 'hashicorp.com' },
  { handle: 'contentful',   name: 'Contentful',   domain: 'contentful.com' },
  { handle: 'algolia',      name: 'Algolia',      domain: 'algolia.com' },
  { handle: 'seismic',      name: 'Seismic',      domain: 'seismic.com' },
  { handle: 'zuora',        name: 'Zuora',        domain: 'zuora.com' },
  { handle: 'sprinklr',     name: 'Sprinklr',     domain: 'sprinklr.com' },
  { handle: 'netlify',      name: 'Netlify',      domain: 'netlify.com' },
  { handle: 'asana',        name: 'Asana',        domain: 'asana.com' },
  { handle: 'brex',         name: 'Brex',         domain: 'brex.com' },
  { handle: 'snap',         name: 'Snap',         domain: 'snap.com' },
  { handle: 'box',          name: 'Box',          domain: 'box.com' },
  { handle: 'elastic',      name: 'Elastic',      domain: 'elastic.co' },
  { handle: 'gitlab',       name: 'GitLab',       domain: 'about.gitlab.com' },
  { handle: 'cloudflare',   name: 'Cloudflare',   domain: 'cloudflare.com' },
];

// ─────────────────────────────────────────────────────────────────────────────
// Filter keywords — also used by server.ts proxy
// ─────────────────────────────────────────────────────────────────────────────

export const PM_KEYWORDS: string[] = [
  'product manager',
  'head of product',
  'director of product',
  'vp of product',
  'chief product officer',
  'product lead',
  'group product manager',
  'principal product',
];

export const LOCATION_KEYWORDS: string[] = [
  'remote',
  'new york',
  ', ny',
  'new jersey',
  ', nj',
  'hybrid',
  'anywhere',
  'united states',
];

// ─────────────────────────────────────────────────────────────────────────────
// Main export — delegates to the server-side proxy at /api/jobs
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetches filtered PM job postings from the local Express proxy at /api/jobs.
 * The proxy handles CORS by fetching Ashby job board pages server-side.
 */
export async function fetchAshbyJobs(): Promise<AshbyJob[]> {
  // In production (GitHub Pages) use pre-built static JSON; in dev use live proxy.
  const url = import.meta.env.PROD ? '/jobs.json' : '/api/jobs';
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Job API returned ${response.status}`);
  return response.json() as Promise<AshbyJob[]>;
}

