// ─────────────────────────────────────────────────────────────────────────────
// Ashby Public Job Board Service
// Fetches live PM job listings from the Ashby public API (no API key required).
// Endpoint: https://api.ashbyhq.com/posting-public/job-board/{handle}
// ─────────────────────────────────────────────────────────────────────────────

export interface AshbyJob {
  id: string;
  title: string;
  company: string;
  companyHandle: string;
  department: string;
  location: string;
  isRemote: boolean;
  employmentType: string;
  publishedDate: string;
  applyUrl: string; // https://jobs.ashbyhq.com/{handle}/{id}
}

// ─────────────────────────────────────────────────────────────────────────────
// Company handles — edit this list to add or remove companies.
// Each string must match the Ashby job board subdomain handle.
// ─────────────────────────────────────────────────────────────────────────────
export const ASHBY_COMPANIES: string[] = [
  '1password',
  '9fin',
  'A1%20Garage%20Door%20Service',
  'Acorns',
  'Adtucon',
  'AlephAlpha',
  'Anon',
  'basis-ai',
  'BranchInsurance',
  'Cambly',
  'Clicklease',
  'Commure-Athelas',
  'credal',
  'Crusoe',
  'CylinderHealth',
  'Dashworks',
  'DatologyAI',
  'DeepL',
  'Deepgram',
  'Distyl',
  'Doowii',
  'DoseSpot',
  'FURTHER',
  'FlutterFlow',
  'Fourier',
  'GPTZero',
  'GoHenry',
  'GradientNetwork',
  'InscribeAI',
  'Jerry',
  'Juicebox',
  'LeanTech',
  'OpenSea',
  'Parkade',
  'Roam',
  'Secoda',
  'Siro',
  'Sonio',
  'Speakeasy',
  'StandardBots',
  'Stepful',
  'Tabs',
  'The-Flex',
  'Vultron',
  'aescape',
  'airapps',
  'airwallex',
  'alan',
  'almedia',
  'altimate',
  'altura',
  'amper',
  'anglehealth',
  'anima',
  'ankorstore',
  'anrok',
  'apify',
  'aptosfoundation',
  'arcade',
  'articul8',
  'artsy',
  'ashby',
  'assembledhq',
  'astera',
  'atob',
  'atroposhealth',
  'auger',
  'august-health',
  'axiom',
  'bankjoy',
  'beam',
  'bedrockocean',
  'benepass',
  'bestow',
  'bettermile',
  'bifrost',
  'blockhouse',
  'blockworks',
  'blueberrypediatrics',
  'boon',
  'botanictonics',
  'brainco',
  'brainly',
  'bratte',
  'bridge',
  'brigit',
  'bunch',
  'cantina',
  'capimoney',
  'captions',
  'carry',
  'casca',
  'centari',
  'character',
  'chronospherejobs',
  'cinder',
  'claylabs',
  'cluely',
  'cohere',
  'cointracker',
  'column',
  'comind',
  'compa',
  'comulate',
  'comun',
  'corti',
  'counsel',
  'count',
  'dakota',
  'dandy',
  'dave',
  'davidenergy',
  'decagon',
  'dedale',
  'deductive',
  'deel',
  'deepwalk',
  'delian',
  'devsavant',
  'dolarapp',
  'doppel',
  'dust',
  'earnedwealth',
  'ekumenlabs',
  'elevenlabs',
  'ema',
  'empora',
  'endex',
  'enode',
  'eotlabs',
  'equi',
  'equip',
  'everai',
  'evertune',
  'fable',
  'farmraise',
  'feathr',
  'fermat',
  'finalis',
  'finary',
  'finch',
  'finvest',
  'fleetpulse',
  'franki',
  'freshpaint',
  'fullstory',
  'g2i',
  'growthtroops',
  'guaranteed',
  'handshake',
  'handspring',
  'harvey',
  'hawk',
  'hcompany',
  'heyjobs',
  'hiive',
  'hims-and-hers',
  'horizon3ai',
  'hotplate',
  'humaans',
  'ideogram',
  'immersivelabs',
  'improbable',
  'integrationapp',
  'invert',
  'january',
  'jigsaw',
  'join9am',
  'joko',
  'julius',
  'junipersquare',
  'keeper',
  'keyrock',
  'kindred',
  'kovo',
  'kraken.com',
  'krea',
  'kustomer',
  'landbase',
  'latitude',
  'leland',
  'letta',
  'lightning',
  'lightspark',
  'lilt',
  'limble',
  'lindushealth',
  'listenlabs',
  'liveflow',
  'lmarena',
  'lucidlink',
  'luma-ai',
  'lunar',
  'mach',
  'mach9',
  'magiceden',
  'magicschool',
  'mainshares',
  'mandolin',
  'mangomint',
  'masabi',
  'mazehq',
  'menlosecurity',
  'metalenz',
  'middesk',
  'mintlify',
  'modernfi',
  'moderntreasury',
  'moego',
  'monarchmoney',
  'mondoo',
  'montecarlodata',
  'mosey',
  'mystenlabs',
  'n8n',
  'netboxlabs',
  'netic',
  'neworbit',
  'niramedical',
  'nomic',
  'notable',
  'numeric',
  'olive',
  'omnea',
  'omniscient',
  'oneapp',
  'onebrief',
  'openai',
  'opengov',
  'oplabs',
  'optery',
  'opusclip',
  'orbitalmaterials',
  'oumi',
  'outliant',
  'pacificfusion',
  'parabola-io',
  'parallel',
  'partiful',
  'partisiablockchain',
  'passage',
  'patreon',
  'peek',
  'phylax',
  'plain',
  'plasmidsaurus',
  'playai',
  'polygon-labs',
  'posthog',
  'primer',
  'privy',
  'projectgrowth',
  'proofofplay',
  'propelus',
  'protege',
  'pylon-labs',
  'quicknode',
  'qventus',
  'raiku',
  'ramp',
  'ravio',
  'reddit',
  'reflectionai',
  'reka',
  'remberg',
  'replit',
  'replo',
  'rilla',
  'rockerbox',
  'rocketsciencegg',
  'rogo',
  'rooser',
  'rula',
  'sardine',
  'scaler',
  'scrollmark',
  'seconddinner',
  'sensmore',
  'sentilink',
  'sesame',
  'siena',
  'silver',
  'skydropx',
  'sleeper',
  'slingshotai',
  'slope',
  'smalls',
  'solace',
  'sona',
  'speak',
  'sprig',
  'stainlessapi',
  'statsig',
  'stealthventurecapitalfirm',
  'stedi',
  'stickermule',
  'stream',
  'suno',
  'supabase',
  'superdial',
  'superduper',
  'surreal',
  'suzy',
  'svix',
  'symbiotic',
  'syndr',
  'synthflow',
  'system2',
  'talentful',
  'tandem',
  'tapcart',
  'taptapsend',
  'tarro',
  'tenex',
  'thatgamecompany',
  'thirstysprout',
  'tonal',
  'traba',
  'tryvital',
  'turnstile',
  'twelve',
  'udisc',
  'uipath',
  'valeriehealth',
  'vanta',
  'vapi',
  'virtahealth',
  'virtuous',
  'vitalize',
  'voladynamics',
  'vooma',
  'wander',
  'warp',
  'waterplan',
  'wayflyer',
  'weave',
  'welltech',
  'winona',
  'withclutch',
  'withpulley',
  'worldlabs',
  'writer',
  'xbowcareers',
  'xoul',
  'yondr',
  'yutori',
  'zapier',
  'zefir',
  'zefr',
  'zencastr',
  'zyphra',
];

// ─────────────────────────────────────────────────────────────────────────────
// Filter keywords — also used by server.ts proxy
// ─────────────────────────────────────────────────────────────────────────────

export const PM_KEYWORDS: string[] = [
  'product manager',
  'head of product',
  'director of product',
  'vp of product',
  'chief product officer',
  'product lead',
  'group product manager',
  'principal product',
];

export const LOCATION_KEYWORDS: string[] = [
  'remote',
  'new york',
  ', ny',
  'new jersey',
  ', nj',
  'hybrid',
  'anywhere',
  'united states',
];

// ─────────────────────────────────────────────────────────────────────────────
// Main export — delegates to the server-side proxy at /api/jobs
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetches filtered PM job postings from the local Express proxy at /api/jobs.
 * The proxy handles CORS by fetching Ashby job board pages server-side.
 */
export async function fetchAshbyJobs(): Promise<AshbyJob[]> {
  const response = await fetch('/api/jobs');
  if (!response.ok) throw new Error(`Job API returned ${response.status}`);
  return response.json() as Promise<AshbyJob[]>;
}

